name: uts_haikalauliaramadhan_241011700587
description: "A new Flutter project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.2.0

  # UI
  salomon_bottom_bar: ^3.3.2
  cherry_toast: ^1.6.0
  simple_alert_dialog: ^1.0.1
  fluttertoast: ^8.2.1

  # Image
  image_picker: ^1.2.0

  # Permission
  permission_handler: ^12.0.1

  # Validation
  email_validator: ^3.0.0
  intl: ^0.20.3

  # Networking
  http: ^1.6.0

  # Maps
  flutter_map: ^8.3.1
  latlong2: ^0.9.1
  geolocator: ^14.0.3
  flutter_map_marker_cluster_plus: ^1.4.2
  flutter_polyline_points: ^3.1.0
  flutter_map_location_marker: ^10.2.0

  # Utilities
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/123.jpeg