// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgybOM8qvvpvzRPwxQ7daJ-Hcs-ldPKQs',
    appId: '1:785352827913:web:d6556a76d964d9732404d8',
    messagingSenderId: '785352827913',
    projectId: 'mobile-programming-proje-cf879',
    authDomain: 'mobile-programming-proje-cf879.firebaseapp.com',
    storageBucket: 'mobile-programming-proje-cf879.firebasestorage.app',
    measurementId: 'G-G6N5HVBPCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Lok9Jqqrg55ea79_jbt_G0th6i-T7ss',
    appId: '1:785352827913:android:3b917b93f16ec43e2404d8',
    messagingSenderId: '785352827913',
    projectId: 'mobile-programming-proje-cf879',
    storageBucket: 'mobile-programming-proje-cf879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDkX6boDk-mYDaxUXs5m3zWkEtZCmGE04',
    appId: '1:785352827913:ios:25bfb1751e75ec502404d8',
    messagingSenderId: '785352827913',
    projectId: 'mobile-programming-proje-cf879',
    storageBucket: 'mobile-programming-proje-cf879.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDkX6boDk-mYDaxUXs5m3zWkEtZCmGE04',
    appId: '1:785352827913:ios:25bfb1751e75ec502404d8',
    messagingSenderId: '785352827913',
    projectId: 'mobile-programming-proje-cf879',
    storageBucket: 'mobile-programming-proje-cf879.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgybOM8qvvpvzRPwxQ7daJ-Hcs-ldPKQs',
    appId: '1:785352827913:web:d399702ae6f073ff2404d8',
    messagingSenderId: '785352827913',
    projectId: 'mobile-programming-proje-cf879',
    authDomain: 'mobile-programming-proje-cf879.firebaseapp.com',
    storageBucket: 'mobile-programming-proje-cf879.firebasestorage.app',
    measurementId: 'G-9WLB5NGDMX',
  );
}
